// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doxulitlitagojznrwux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRveHVsaXRsaXRhZ29qem5yd3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MjYzMTQsImV4cCI6MjA2ODEwMjMxNH0.bEOnpUOSe8JLONFnJHiSE6r5M1DRQc6C6Ce15-XjC3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});